const config = {
    "listen": "Listening on port",
    "token" : "No token found in cookies",
    db : {
        "connected" : "Connected to database",
        "err" : "Error connecting to database",
        "login": "Login successful",
        "username": "Error in username",
        "password": "Error in password",
        "email": "Error in email",
        "user": "User already exists",
        "register": "Registration successful",
        "credentials": "Invalid credentials",
        "register_err": "Registration failed",
    },
    "api" : "Error updating api calls",
    "server" : "Error connecting to server",
    "user_info" : "Error querying user information:",
    "api_calls" : "Error querying api calls:",
    "description" : "Error updating description:",
    "resume-feedback" : "Error updating resume feedback:",
    "job-feedback" : "Error updating job feedback:",
    "calls_counter" : "Error updating calls counter:",
    "login_counter" : "Error updating login counter:",
    "userinfos" : "Error updating userinfos:",
    "delCounter" : "Error updating deleting counter:",
    "updateSuccess" : "Update successful",
   };
   
   module.exports = config;